Resources:
  NestedCall:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://vitaws.s3.ap-southeast-1.amazonaws.com/nested.yaml
      TimeoutInMinutes: 60
Outputs:
  StackRef:
    Value: !Ref NestedCall
  OutputFromNestedStack:
    Value: !GetAtt NestedCall.Outputs.BucketName