AWSTemplateFormatVersion: '2010-09-09'
Description: A sample template
Resources:
  MyEC2Instance: #An inline comment
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0ff89c4ce7de192ea' #Another comment -- This is a Linux AMI
      InstanceType: t2.micro
      Tags:
        - Key: 'Name'
          Value: 'This is EC2 instance with new tags'
