Parameters:
  ResourceName:
    Description: 'The name of the service this stack is to be used for.'
    Type: String
  KeyName:
    Description:
      Name of an existing EC2 KeyPair to enable SSH access into the server
    Type: AWS::EC2::KeyPair::KeyName
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-090fa75af13c156b4
    ap-southeast-1:
      AMI: ami-0ff89c4ce7de192ea
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: 'Name'
          Value: !Ref ResourceName
      KeyName: !Ref KeyName
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
Outputs:
  ServerDns:
    Value: !GetAtt
      - Ec2Instance
      - PublicDnsName
#Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html


# Outputs cho phép bạn xuất ra các giá trị từ các resources được tạo ra trong quá trình tạo ra một stack. Các giá trị này có thể được sử dụng bởi các stack khác hoặc các ứng dụng khác trong AWS.
# Nếu sử dụng outputs trong template thì sau khi RUN template này, ta có thể vào cloudformation rồi chọn tab"OUTPUT" để xem kết quả đc export ra.